/**
 * Generate Files API Endpoint
 * Creates console-specific setup files from session mix
 */

import { NextRequest, NextResponse } from 'next/server';
import JSZip from 'jszip';
import { sessionManager } from '@/lib/ai/memory';
import { YamahaAdapter } from '@/lib/adapters/yamaha';
import { UniversalMix } from '@/lib/models/universal-mix';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { sessionId, format = 'yamaha-csv', includeDocumentation = true } = body;

    // Validate session
    if (!sessionId) {
      return NextResponse.json(
        { error: 'sessionId required' },
        { status: 400 }
      );
    }

    const session = sessionManager.get(sessionId);
    if (!session) {
      return NextResponse.json(
        { error: 'Session not found' },
        { status: 404 }
      );
    }

    // Get current mix
    const mix = sessionManager.getCurrentMix(sessionId);
    if (!mix) {
      return NextResponse.json(
        { error: 'No mix data in session. Build a mix first using the chat.' },
        { status: 400 }
      );
    }

    // Generate files based on format
    let files: { name: string; content: string; type: string }[] = [];

    switch (format) {
      case 'yamaha-csv': {
        const adapter = new YamahaAdapter();
        const adapterFiles = adapter.generate(mix as UniversalMix);

        files = adapterFiles
          .filter((f) => includeDocumentation || f.name.endsWith('.csv'))
          .map((f) => ({
            name: f.name,
            content: f.content,
            type: f.name.endsWith('.csv') ? 'csv' : 'md',
          }));
        break;
      }

      case 'x32-scene':
        return NextResponse.json(
          { error: 'X32/M32 format not yet implemented' },
          { status: 501 }
        );

      case 'dlive-show':
        return NextResponse.json(
          { error: 'Allen & Heath dLive format not yet implemented' },
          { status: 501 }
        );

      default:
        return NextResponse.json(
          { error: `Unknown format: ${format}` },
          { status: 400 }
        );
    }

    // Create ZIP archive
    const zip = new JSZip();
    const gigName = (mix as UniversalMix).gig?.name || 'GigPrepper';
    const safeName = gigName.replace(/[^a-zA-Z0-9åäöÅÄÖ_-]/g, '_');
    const folderName = `${safeName}_${format}`;

    // Add files to appropriate folders
    const csvFolder = zip.folder(`${folderName}/CSV`);
    const docsFolder = zip.folder(`${folderName}/Documentation`);

    for (const file of files) {
      if (file.type === 'csv') {
        csvFolder?.file(file.name, file.content);
      } else {
        docsFolder?.file(file.name, file.content);
      }
    }

    // Add a README at root
    zip.file(
      `${folderName}/README.txt`,
      `Gig-Prepper Export
==================

Gig: ${(mix as UniversalMix).gig?.name || 'Unnamed'}
Date: ${new Date().toISOString().split('T')[0]}
Console: ${(mix as UniversalMix).console?.manufacturer} ${(mix as UniversalMix).console?.model}
Format: ${format}

Folder Contents:
- CSV/       Console import files (copy to USB)
- Documentation/  Setup guides and recommendations

Import Instructions (Yamaha CL/QL):
1. Copy CSV folder contents to USB drive (FAT32)
2. Insert USB into console
3. Go to SETUP > SAVE/LOAD
4. Select USB > LOAD > LOAD LIBRARY
5. Import each file type as needed

For detailed EQ, dynamics, and effects settings,
refer to the documentation files.

Generated by Gig-Prepper AI Sound Engineer
https://github.com/joelkvarnsmyr/Gig-prepper
`
    );

    // Generate ZIP
    const zipBlob = await zip.generateAsync({
      type: 'base64',
      compression: 'DEFLATE',
      compressionOptions: { level: 6 },
    });

    // Return response with ZIP data
    return NextResponse.json({
      success: true,
      filename: `${folderName}.zip`,
      content: zipBlob,
      contentType: 'application/zip',
      fileCount: files.length,
      csvCount: files.filter((f) => f.type === 'csv').length,
      docCount: files.filter((f) => f.type === 'md').length,
      format,
      instructions: [
        '1. Ladda ner ZIP-filen',
        '2. Extrahera innehållet',
        '3. Kopiera CSV-filerna till ett USB-minne (FAT32)',
        '4. Importera på konsolen via SETUP > SAVE/LOAD',
        '5. Läs dokumentationen för EQ/dynamik/effekter',
      ],
    });
  } catch (error) {
    console.error('Generate error:', error);
    return NextResponse.json(
      { error: `Failed to generate files: ${error instanceof Error ? error.message : 'Unknown error'}` },
      { status: 500 }
    );
  }
}

/**
 * GET endpoint - get available formats
 */
export async function GET() {
  return NextResponse.json({
    formats: [
      {
        id: 'yamaha-csv',
        name: 'Yamaha CL/QL/TF CSV',
        description: 'CSV-filer för USB-import på Yamaha CL, QL och TF-serien',
        supported: true,
        consoles: ['CL1', 'CL3', 'CL5', 'QL1', 'QL5', 'TF1', 'TF3', 'TF5'],
      },
      {
        id: 'x32-scene',
        name: 'Behringer X32 / Midas M32 Scene',
        description: '.scn scene-filer för X32 och M32',
        supported: false,
        consoles: ['X32', 'X32 Compact', 'X32 Producer', 'M32', 'M32R'],
      },
      {
        id: 'dlive-show',
        name: 'Allen & Heath dLive Show',
        description: 'Show-filer för dLive-serien',
        supported: false,
        consoles: ['dLive S3000', 'dLive S5000', 'dLive S7000', 'Avantis'],
      },
    ],
  });
}
